# Generated by Django 5.2.6 on 2025-09-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='description',
            field=models.CharField(default='no descrizione', max_length=100),
        ),
    ]
