# Generated by Django 5.2.6 on 2025-09-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_roll_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='description',
            field=models.CharField(default='no descrizione', max_length=255),
        ),
    ]
